### ISSUE TITLE
When should I call the await httpTerminator.terminate();

### ISSUE THREAD

**Issue by rubenrajkowski-nbcuni** [gajus/http-terminator#15]
I assume I have to wrap this in a `async` method or callback like `process.on('SIGTERM', callback)`.  
When do you recommend I run the  `await httpTerminator.terminate()` call?

Thanks Ruben

**Comment by gajus** [comment]
You'd usually use it either because some error occurred that requires you to terminate the service or because you've received an external signal (such as `SIGTERM` example you gave).

I use `http-terminator` in combination with https://github.com/gajus/lightship to terminate my services when Kubernetes instructs to shutdown the service.

**Comment by roychowdhuryrohit-dev** [comment]
@gajus Is it necessary to call `await httpTerminator.terminate()` after this?
```
const httpTerminator = createHttpTerminator({
  server
});
```

```
SyntaxError: await is only valid in async function
```
